version: '3.5'

services:
  dynamo:
    container_name: dynamodb-local
    image: amazon/dynamodb-local
    networks:
      - monsternames
    ports:
      - '8000:8000'

  monsternames:
    depends_on:
      - dynamo
    networks:
      - monsternames
    build:
      context: ./
      dockerfile: dockerfile
    ports:
      - '9000:8080'
    volumes:
      - './config.ini:/home/config.ini'
    environment:
      config_file: '/home/config.ini'

networks:
  monsternames:
    name: monsternames