name: Python checks on pull request

on: [pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
    - name: Lint with Ruff
      run: |
        pip3 install ruff
        ruff check --output-format=github .
      continue-on-error: true
    - name: Run behavioural tests
      run: |
        make execute-behaviour-tests
      continue-on-error: true

